<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <OutputType>WinExe</OutputType>
	<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <PackageIcon>Gersang_Tracker.png</PackageIcon>
	<AssemblyVersion>2.2.2.0</AssemblyVersion>
	<FileVersion>2.2.2.0</FileVersion>
	<Version>2.2.2.0</Version>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
	<AssemblyTitle>GersangTracker</AssemblyTitle>
	<Description>거상 트래커</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="favicon.ico" />
    <Content Include="Assets\7za.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="EPPlus" Version="8.5.0" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="6.2.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="PacketDotNet" Version="1.4.8" />
    <PackageReference Include="SharpPcap" Version="6.3.1" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\..\Downloads\Gersang_Tracker\res\mipmap-hdpi\Gersang_Tracker.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\favicon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\GersangItems.json" />
  </ItemGroup>
</Project>
